// Shared media import/processing types, used by the main process, preload
// bridge, and renderer UI (Phase B).

export const SUPPORTED_VIDEO_AUDIO_EXTENSIONS = ['mp4', 'mov', 'webm', 'mp3', 'wav', 'm4a', 'mkv'] as const
/** Still images are imported like any other clip -- see stillImage.ts, which
 * synthesizes a fixed-duration silent video from the image on import so
 * playback, the timeline, proxy generation, and export never special-case
 * images; they only ever see a real video file. */
export const SUPPORTED_IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'webp', 'bmp'] as const
export const SUPPORTED_MEDIA_EXTENSIONS = [...SUPPORTED_VIDEO_AUDIO_EXTENSIONS, ...SUPPORTED_IMAGE_EXTENSIONS] as const

export type MediaKind = 'video' | 'audio'

export interface MediaMetadata {
  durationSeconds: number
  width?: number
  height?: number
  frameRate?: number
  videoCodec?: string
  audioCodec?: string
  hasVideo: boolean
  hasAudio: boolean
  containerFormat: string
  fileSizeBytes: number
}

export type MediaProcessingStage =
  | 'queued'
  | 'validating'
  | 'probing'
  | 'thumbnail'
  | 'waveform'
  | 'proxy'
  | 'ready'
  | 'error'
  | 'canceled'

export interface WaveformData {
  /** Interleaved [min, max] pairs per bucket, normalized to -1..1 */
  peaks: number[]
  sampleRate: number
  bucketCount: number
}

export interface MediaItem {
  id: string
  kind: MediaKind
  /** Which real-world asset kind this came from -- see
   * shared/project.ts's MediaSource.assetType doc comment (a still image is
   * imported by synthesizing a short silent video from it, so `kind` stays
   * 'video' while `assetType` records that it's really an image). */
  assetType?: 'video' | 'image' | 'audio'
  fileName: string
  originalPath: string
  originalUrl: string
  proxyPath?: string
  proxyUrl?: string
  thumbnailPath?: string
  thumbnailUrl?: string
  waveform?: WaveformData
  metadata?: MediaMetadata
  stage: MediaProcessingStage
  percent: number
  errorMessage?: string
  cached: boolean
  addedAt: string
}

export interface MediaProgressUpdate extends Partial<MediaItem> {
  mediaId: string
  stage: MediaProcessingStage
  percent: number
}

export interface FfmpegAvailability {
  ffmpeg: boolean
  ffprobe: boolean
  ffmpegVersion?: string
  ffprobeVersion?: string
  error?: string
}

export const MEDIA_IPC = {
  pickFiles: 'media:pickFiles',
  importPaths: 'media:importPaths',
  cancelJob: 'media:cancelJob',
  retryJob: 'media:retryJob',
  progress: 'media:progress',
  ffmpegStatus: 'media:ffmpegStatus',
  /** Reconstructs ready-to-play MediaItems (fresh app-media:// tokens) from a
   * loaded project's persisted MediaSource[] -- re-registers protocol tokens
   * for the already-processed proxy/thumbnail/original files on disk without
   * re-running ffmpeg probing, since every field it needs was already saved. */
  rehydrate: 'media:rehydrate',
  /** Writes renderer-generated bytes (a Freeze Frame PNG, a Voiceover
   * recording) to a real file under the project-managed media cache and
   * returns its path -- the renderer then feeds that path through the exact
   * same importPaths pipeline every imported file already goes through,
   * rather than a parallel ingest path. */
  saveGeneratedFile: 'media:saveGeneratedFile'
} as const
